### ISSUE TITLE
ERROR Couldn't retrieve clip URL

### ISSUE THREAD

**Issue by JustinFourie** [Ebram-Tharwat/CSharp-Pluralsight-Downloader#30] opened 2017-01-03 11:31 UTC
Hi

Thanks for this app its really useful .

I have a bug though , I can download  files from a course but after a few download I get this error "ERROR Couldn't retrieve clip URL" .

To get it to work again I have to stop the application,close Visual Studio  and re run it , it seems like the Authentication token expires and causes this . I did some testing and it seems to do this after about 15 minits of downloading each time , the error also only shows up when it starts downloading a file. If a file is still downloading when the 15 min mark is reached it does not error.

I have tried changin my password this did nto help . I have tried downloading a few files by clicking the individual download buttones  as well , still got the same error after a 3 or 4 files  . I have also tried clicking _Download the whooole course!_  this also resulted in the same error .

**Information** 

_The course link I am using_ : https://app.pluralsight.com/library/courses/powershell-and-sql-server/table-of-contents

_My password_ : It contains uper and lowe case caracters and some numbers .

_Error from the log file_ 

> 2017-01-03 13:11:24.6397 TRACE System.Exception: Couldn't retrieve clip URL. Please check log file.
>    at PluralsightDownloader.Web.Controllers.CourseController.GetClipUrl(ClipToSave clip) in c:\Users\justinfo\Downloads\CSharp-Pluralsight-Downloader-master\CSharp-Pluralsight-Downloader-master\PluralsightDownloader.Web\Controllers\CourseController.cs:line 227
>    at PluralsightDownloader.Web.Controllers.CourseController.<DownloadCourseModuleClip>d__d.MoveNext() in c:\Users\justinfo\Downloads\CSharp-Pluralsight-Downloader-master\CSharp-Pluralsight-Downloader-master\PluralsightDownloader.Web\Controllers\CourseController.cs:line 86

**Comment by Ebram-Tharwat** [comment] 2017-01-03 13:05
@JustinFourie , as I understand from you issue, you download first 3 or 4 clips normally but after that you get error that get fixed by restarting the app, right?

I will try to download your course and see if I will get the same error or not. But, in the meanwhile:

- Can you try to debug the code to get more info on that error. maybe check the response from `LoginToPluralSight` and `GetClipUrl` methods.
- Do you get this error with this course only, or it happens with other courses too.
- Do you use the latest update of the app, if not, can you please update your files and try again.

**Comment by JustinFourie** [comment] 2017-01-03 13:42
Hi , thanks for the fast response.

Please see below to the answers to your questions 

_Do you use the latest update of the app_ : Yes I downlaoed a zip of the repository today and tested with this version . Only tried the app for the first time today. 

_Do you get this error with this course only_ : I have tired with 3 diffrent courses .

_Can you try to debug the code to get more info on that erro_rror : I am not really a dev and when I add the break points It seems to just cause errors and the app not to work . 

One thing I did notice is that there does seem to be some sort of time out in the video url when you request it . Example below , So may be if it errors out calling GetClipUrl it should try re-login 
`
http://vid.pluralsight.com/expiretime=1483453250/c82cb962295629043a6248ace9b145d4/clip-videos/kathi-kellenberger/tsql-window-functions-m4/tsql-window-functions-m4-06/1280x720mp4/20151208053528.mp4`

**Comment by Ebram-Tharwat** [comment] 2017-01-04 01:25
@JustinFourie , I tried to download your course and it working fine. Also, I checked the `expiretime` which is in most cases equal to an hour after the request was initiated.

I don't want to do quick fix (clear cookie whenever error happen), so can you please replace the code at `CourseController.cs` line 224 with the following (i'm just logging the exception):
```
catch(Exception ex)
{
  logger.Error(ex);
  logger.Error("Couldn't retrieve clip URL. Request parameters={0}", JsonConvert.SerializeObject(playerParametersObj));                
  throw new Exception("Couldn't retrieve clip URL. Please check log file.");
}
```
Then try again and let me know the error logged in the log file.

**Comment by JustinFourie** [comment] 2017-01-04 06:21
Thanks , I have made the change and tried again . got the same error as before after 15 mins .
This was what I got in the error log .

2017-01-04 08:16:47.6605 ERROR System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at PluralsightDownloader.Web.Controllers.CourseController.GetClipUrl(ClipToSave clip) in c:\Users\justinfo\Downloads\CSharp-Pluralsight-Downloader-master\CSharp-Pluralsight-Downloader-master\PluralsightDownloader.Web\Controllers\CourseController.cs:line 216
 ------------------------------------------------------------
2017-01-04 08:16:47.6775 ERROR Couldn't retrieve clip URL. Request parameters={"a":"kathi-kellenberger","m":"tsql-window-functions-m7","course":"tsql-window-functions","cn":"2","mt":"mp4","q":"1280x720","cap":false,"lc":"en"}
 ------------------------------------------------------------
2017-01-04 08:16:47.7093 TRACE System.Exception: Couldn't retrieve clip URL. Please check log file.
   at PluralsightDownloader.Web.Controllers.CourseController.GetClipUrl(ClipToSave clip) in c:\Users\justinfo\Downloads\CSharp-Pluralsight-Downloader-master\CSharp-Pluralsight-Downloader-master\PluralsightDownloader.Web\Controllers\CourseController.cs:line 228
   at PluralsightDownloader.Web.Controllers.CourseController.<DownloadCourseModuleClip>d__d.MoveNext() in c:\Users\justinfo\Downloads\CSharp-Pluralsight-Downloader-master\CSharp-Pluralsight-Downloader-master\PluralsightDownloader.Web\Controllers\CourseController.cs:line 86
 ------------------------------------------------------------

**Comment by Ebram-Tharwat** [comment] 2017-01-04 10:13
@JustinFourie , that's strange.

I tried to download the same clip in the same course and it works fine. **`(401) Unauthorized`**, means you are not allowed to access the site or make request. I tried to put dummy authentication cookie or send wrong parameters, but I get **`(400) Bad Request`**

Are you **sure** that you are able to watch the files normally through pluralsight website ??

**Comment by Ebram-Tharwat** [comment] 2017-01-07 15:05
@JustinFourie , any updates on this issue?

**Comment by JustinFourie** [comment] 2017-01-07 15:40
Hi , 

I have figured out the problem it is some thing to do with the fire wall at work (sorry cant give you any details about this). 
Using the same pc at home and not going though the company fire wall it works fine . 
So it must be some thing to do with the fire wall and how it cache's the credentials . Would be interesting to know why it works like that . I can watch multiple videos after each other at work on the website .

So it just seems the way the authentication is done in the app is some how different to the browser.

**Comment by Ebram-Tharwat** [comment] 2017-01-08 16:16
@JustinFourie , glad you managed to find out the cause of this issue.

Regarding authentication, i guess on the browser, auth cookie is refreshed when you stay active after some time.

**Closed by Ebram-Tharwat** 2017-01-08 16:16 UTC
Labels: bug
